use std::str::FromStr;
use crate::parser::ast::{Schema, Relation, Table, Join, View};

grammar;

pub Schema: Schema = {
    <r:Relation*> => Schema {
        rels: r,
    }
};

pub Relation: Relation = {
    Table => Relation::Table(<>),
    Join => Relation::Join(<>),
    View => Relation::View(<>),
}

pub Table: Table = {
    "table" => panic!(),
}

pub Join: Join = {
    "join" => panic!(),
}

pub View: View = {
    "view" => panic!(),
}
